# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

runLinearisedSISModel <- function(lambda, gamma, max_time) {
    .Call(`_tmi_runLinearisedSISModel`, lambda, gamma, max_time)
}

runIndividualSISModel <- function(beta, gamma, num_individuals, num_infected, max_time) {
    .Call(`_tmi_runIndividualSISModel`, beta, gamma, num_individuals, num_infected, max_time)
}

runIndividualSIIModel <- function(beta, gamma, num_individuals, num_infected, max_time) {
    .Call(`_tmi_runIndividualSIIModel`, beta, gamma, num_individuals, num_infected, max_time)
}

